//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloneShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int ReceiptID { get; set; }
        public int OrderID { get; set; }
        public string PdfPath { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
