//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloneShop.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramLinks
    {
        public int TelegramLinkID { get; set; }
        public string Url { get; set; }
        public string QrImagePath { get; set; }
        public bool IsActive { get; set; }
    }
}
